module.exports ={
  type:"pageview",
  root:["header","body"],
  style:{"backgroundColor":"#f7f7f7"},
  components:{
    header:{
      type:"xz.header",
      root:["退出","headertitle"],
      style:{
        common:"header"
      }
    },
    headertitle:{
      type:"xz.text",
      text:"全部订单",
      style:{
        color:"#fff",
        fontSize:17
      },
      onClick:[
        {type:"navigate",to:"buttons"}
      ]
    },
    退出:{
      type:"xz.icon",
      font:"icomoon_e960",
      style:{common:"lefticon",justifyContent:"flex-start"},
      iconStyle:{color:"#fff",fontSize:18},
      onClick:[
        {type:"goback"}
      ]
    },
    body:{
      type:"xz.view",
      root:["segment1","ViewPager"],
      style:{
        flex:1
      }
    },
    segment1:{
      type:"xz.segment",
      styletype:"2",
      changewith:"ViewPager",
      items:["全部","待付款","待发货","待收货","待评价"],
      style:{
        borderColor:"#ccc",
        backgroundColor:"#fff"
      },
      selectedTextStyle:{
        color:"#FF6633"
      },
      textStyle:{
        fontSize:14,
        color:"gray",
      },
      indicatorStyle:{
        backgroundColor:"#FF6633"
      },
      itemStyle:{
        height:40,
      }
    },
    ViewPager:{
      type:"xz.viewpager",
      style:{
        flex:1,
        backgroundColor:"#eee"
      },
      views:["viewpager_1","viewpager_2","viewpager_3","viewpager_4","viewpager_5"]
    },
    viewpager_1:{
      type:"xz.view",
      style:{
        flex:1,
        backgroundColor:"red",
      },
      root:["viewpage1_text1"]
    },
    viewpage1_text1:{
      type:"xz.text",
      text:"sdasdas"
    },
    viewpager_2:{
      type:"xz.view",
      style:{
        flex:1,
        backgroundColor:"yellow"
      },
      root:["viewpager_2_segment"]
    },
    viewpager_2_segment:{
      type:"xz.segment",
      items:["好评","中评","差评"],
      style:{
        width:240,
        marginTop:20,
        alignSelf:"center",
        borderColor:"green"
      },
      itemStyle:{
        borderColor:"green"
      },
      selectedItemStyle:{
        backgroundColor:"green"
      }
    },
    viewpager_3:{
      type:"xz.view",
      style:{
        flex:1,
        backgroundColor:"orange"
      }
    },
    viewpager_4:{
      type:"xz.view",
      style:{
        flex:1,
        backgroundColor:"gray"
      }
    },
    viewpager_5:{
      type:"xz.view",
      style:{
        flex:1,
        backgroundColor:"green"
      }
    }
  }
}
