module.exports = {
  type:"pageview",
  root:["头部","topview","body"],
  components:{
    topview:{
      type:"xz.view",
      style:{
        height:120,
        backgroundColor:"lightblue"
      }
    },
    body:{
      type:"xz.view",
      scrollEnabled:true,
      style:{
        flex:1
      },
      root:["innerView"]
    },
    innerView:{
      type:"xz.view",
      style:{
        width:100,
        height:1000
      },
      root:["setting_text1"]
    },
    setting_text1:{
      type:"xz.text",
      text:"setting",
      style:{color:"red"}
    },头部:{
      type:"xz.header",
      root:["退出","headertitle","headerRightIcon"],
      style:{
        common:"header"
      }
    },
    退出:{
      type:"xz.icon",
      font:"icomoon_e960",
      style:{common:"lefticon",width:55},
      iconStyle:{color:"#fff",fontSize:18},
      textStyle:{color:"#fff"},
      text:"退出",
      onClick:[
        {type:"goback"}
      ]
    },
    headertitle:{
      type:"xz.text",
      text:"Setting",
      style:{
        color:"#fff",
        fontSize:17
      }
    },
    headerRightIcon:{
      type:"xz.icon",
      font:"icomoon_e914",
      iconStyle:{color:"#fff",fontSize:20},
      style:{
        common:"righticon"
      }
    }
  }
}
