module.exports = {
  type:"pageview",
  style:{
    backgroundColor:"#F9F9F9"
  },
  root:["头部","menulayout1","menulayout2"],
  components:{
    menulayout1:{
      type:"xz.menulayout",
      style:{marginTop:10},
      root:["扫一扫","摇一摇","设置"]
    },
    menulayout2:{
      type:"xz.menulayout",
      style:{marginTop:10},
      root:["附近","漂流瓶"]
    },
    附近:{
      type:"xz.view",
      root:["附近图标","righticon-fj"],
      style:{
        common:["MenuLayoutItem"]
      }
    },附近图标:{
      type:"xz.icon",
      text:"附近",
      font:"icomoon_e935",
      iconStyle:{color:"#0093ff",fontSize:20},
      textStyle:{color:"#292F33",fontSize:17,marginLeft:16,marginBottom:1},
      textPos:"right"
    },
    漂流瓶:{
      type:"xz.view",
      root:["漂流瓶图标","righticon-plp"],
      style:{
        common:["MenuLayoutItem"]
      }
    },漂流瓶图标:{
      type:"xz.icon",
      text:"漂流瓶",
      font:"icomoon_e923",
      iconStyle:{color:"#0093ff",fontSize:20},
      textStyle:{color:"#292F33",fontSize:17,marginLeft:16,marginBottom:1},
      textPos:"right"
    },
    扫一扫:{
      type:"xz.view",

      root:["扫一扫图标","righticon-1"],
      style:{
        common:["MenuLayoutItem"]
      },
      onClick:[
        {"type":"navigate",to:"saoyisao"}
      ]
    },
    摇一摇:{
      type:"xz.view",
      root:["摇一摇图标","righticon-2"],
      style:{
        common:["MenuLayoutItem"]
      },
      onClick:[
        {type:"modifyStyle",page:"page1",to:"page1_text2",color:"red",fontSize:23},
        {type:"modifyStyle",page:"page1",to:"page1_view1",backgroundColor:"#fff"},
        {type:"modifyProperty",page:"page1",to:"page1_text3",text:"跳转到Page00"}
      ]
    },设置:{
      type:"xz.view",
      root:["设置图标","righticon-3"],
      style:{
        common:["MenuLayoutItem"]
      }
    },
    摇一摇图标:{
      type:"xz.icon",
      text:"摇一摇",
      font:"icomoon_e92f",
      iconStyle:{color:"#0093ff",fontSize:20},
      textStyle:{color:"#292F33",fontSize:17,marginLeft:16,marginBottom:1},
      textPos:"right"
    },
    设置图标:{
        type:"xz.icon",
        text:"设置",
        font:"icomoon_e928",
        iconStyle:{color:"#0093ff",fontSize:20},
        textStyle:{color:"#292F33",fontSize:17,marginLeft:16,marginBottom:1},
        textPos:"right"
      },
    扫一扫图标:{
      type:"xz.icon",
      text:"扫一扫",
      font:"icomoon_e920",
      iconStyle:{color:"#0093ff",fontSize:20},
      textStyle:{color:"#292F33",fontSize:17,marginLeft:16,marginBottom:1},
      textPos:"right"
    },
    头部:{
      type:"xz.header",
      root:["退出","headertitle","headerRightIcon"],
      style:{
        common:"header"
      }
    },
    退出:{
      type:"xz.icon",
      font:"icomoon_e960",
      iconStyle:{color:"#fff",fontSize:18},
      textStyle:{color:"#fff"},
      text:"退出",
      style:{common:"lefticon",width:55},
      onClick:[
        {type:"goback"}
      ]
    },
    headertitle:{
      type:"xz.text",
      text:"Why",
      style:{
        color:"#fff",
        fontSize:17
      }
    },
    headerRightIcon:{
      type:"xz.icon",
      font:"icomoon_e914",
      iconStyle:{color:"#fff",fontSize:20},
      style:{
        common:"righticon"
      }
    }
  }
}
