module.exports = {
  type:"pageview",
  root:["header","body"],
  style:{"backgroundColor":"#fff"},
  components:{
    header:{
      type:"xz.header",
      root:["退出","headersegment"],
      style:{
        common:"header",
        backgroundColor:"#fff"
      }
    },
    headersegment:{
      type:"xz.segment",
      styletype:"2",
      items:["商品","详情","评价"],
      style:{
        width:150
      },
      itemStyle:{
        ios_height:38,
        android_height:48,
        web_height:48,
      },
      textStyle:{
        fontSize:15
      },
      selectedTextStyle:{
        color:"black",
        fontSize:15
      },
      indicatorStyle:{
        backgroundColor:"black"
      }
    },
    退出:{
      type:"xz.icon",
      font:"icomoon_e960",
      style:{common:"lefticon",justifyContent:"flex-start"},
      iconStyle:{color:"#000",fontSize:18},
      onClick:[
        {type:"goback"}
      ]
    },
    body:{
      type:"xz.view",
      overflow:"auto",
      style:{
        flex:1
      },
      root:[
        "goodsdetail_swiper"
      ]
    },
    goodsdetail_swiper:{
      type:"xz.swiper",
      style:{
        height:290
      }
    },
  }
}
