module.exports ={
  type:"pageview",
  root:["头部","view1","line1-1"],
  components:{
    头部:{
      type:"xz.header",
      root:["退出","headertitle","headerRightIcon"],
      style:{
        common:"header"
      }
    },
    退出:{
      type:"xz.icon",
      font:"icomoon_e960",
      iconStyle:{color:"#fff",fontSize:18},
      textStyle:{color:"#fff"},
      text:"退出",
      style:{common:"lefticon",
      width:55},
      onClick:[
        {type:"goback"}
      ]
    },
    headertitle:{
      type:"xz.text",
      text:"What",
      style:{
        color:"#fff",
        fontSize:17
      }
    },
    headerRightIcon:{
      type:"xz.icon",
      font:"FontAwesome_f007",
      iconStyle:{color:"#fff",fontSize:20},
      style:{
        common:"righticon"
      },
      onClick:[
        {type:"showpage",to:"sliderP"}
      ]
    }
  }
}
