 module.exports = {
  type:"pageview",
  isRoot:true,
  primaryKey:{
    RepeatData:"id",
    GoodsListView:["id","id2"]
  },
  dataSource:{
    GoodsListView:{
      url:"/test",
      type:"GET",
      params:{"pageindex":1,"pagesize":10,"sorttype":5,"category":"010041JZ28DL153TP045"},
    },
    RepeatData:[
        {id:1,"icon":"icomoon_e935","name":"Home","count":"12"},
        {id:2,"name":"我的","count":"0","icon":"icomoon_e90f"},
        {id:3,"name":"标题","count":"0","icon":"icomoon_e928"}
      ]
  },
  style:{
    backgroundColor:"rgb(243, 243, 243)"
  },
  root:[
    "page1_header",
    "page1_body","popover"
  ],
  components:{
    page1_header:{
      type:"xz.header",
      root:["headersegment","headerLeftIcon"],
      style:{
        common:"header"
      }
    },
    headersegment:{
      type:"xz.segment",
      styletype:"1",
      style:{
        width:120,
        borderColor:"white",
        borderRadius:6
      },
      selectedItemStyle:{
        backgroundColor:"white"
      },
      selectedTextStyle:{
        color:"rgb(18,181,242)"
      },
      itemStyle:{
        height:25,
        borderLeftColor:"transparent",
        backgroundColor:"rgb(18,181,242)"
      },
      textStyle:{
        fontSize:13,
        color:"white"
      },
      items:["消息","电话"]
    },
    page1_swiper:{
      type:"xz.swiper",
      style:{
        height:180
      }
    },
    headerempty:{
      type:"xz.view",
      style:{
        width:40
      }
    },
    page1_body:{
      type:"xz.view",
      scrollEnabled:true,
      root:["page1_swiper","page1_view1",
      "page1_segment",
      "page1_segment1","page1_segment2","page1_segment3","page1_segment4",
      "page1_view2",
      "line1-1",
      "page1_text2",
      "page1_testBtn",
      "page1_text3",
      "line1-2","yunfeiview","line1-3","listviewtitlewrapper","repeat","listview"],
      style:{
        flex:1
      }
    },
    repeat:{
      selectedmode:"s",//or m,
      type:"xz.repeat",
      datasource_bind:"RepeatData",
      style:{flexDirection:"row",height:48,alignItems:"center",backgroundColor:"#313541"},
      root:["itemview"],
      itemStyle:{
        flex:1,height:48,justifyContent:"center",alignItems:"center"
      },
    },
    itemview:{
      type:"xz.view",
      style:{},
      root:["re_icon","re_text1"]
    },
    re_icon:{
      type:"xz.icon",
      selectedcolor:"#0093FF",
      font_bind:"$$rowdata.icon",
      iconStyle:{fontSize:22,color:"#677785"},
      style:{textAlign:"center"}
    },
    re_text1:{
      type:"xz.text",
      text_bind:"$$rowdata.name",
      style:{textAlign:"center",marginTop:2,fontSize:11,color:"#677785"},
      text:""
    },
    page1_testBtn:{
      type:"xz.button",
      text:"测试跳往同一页面",
      style:{
      },
      onClick:[]
    },
    page1_segment:{
      type:"xz.segment",
      style:{
        marginTop:5,
        marginBottom:5,
        alignSelf:"center",
        borderColor:"orange"
      },
      selectedItemStyle:{
        backgroundColor:"orange"
      },
      textStyle:{
        color:"gray"
      },
      itemStyle:{
        width:80,
        height:26,
        borderLeftColor:"orange"
      }
    },
    page1_segment3:{
      type:"xz.segment",
      styletype:"2",
      items:["国外","国内","xx"],
      style:{
        borderRadius:16,
        overflow:"hidden",
        width:220,
        marginLeft:20,
        backgroundColor:"rgb(43,62,77)",

      },
      itemStyle:{
        height:32,
        backgroundColor:"transparent"
      },
      textStyle:{
        color:"white"
      },
      selectedTextStyle:{
        color:"#fff"
      },
      selectedItemStyle:{

      },
      indicatorStyle:{
        height:32,
        borderRadius:16,
        backgroundColor:"rgb(143,173,220)"
      }
    }
    ,page1_segment1:{
      type:"xz.segment",
      styletype:"2",
      items:["精选","军事","纪录片","动漫","电影","电视剧","综艺","推荐"],
      style:{
        borderColor:"#ccc"
      },
      selectedTextStyle:{
        color:"red"
      },
      textStyle:{
        fontSize:13,
        color:"gray",
      },
      indicatorStyle:{
        backgroundColor:"rgb(108, 170, 255)"
      },
      itemStyle:{
        width:60,
        height:34,
      }
    },
    page1_segment2:{
      type:"xz.segment",
      styletype:"2",
      items:["精选","军事","纪录片","动漫","电影","电视剧","综艺","推荐"],
      style:{
        borderColor:"#ccc"
      },
      selectedTextStyle:{
        color:"red"
      },
      textStyle:{
        fontSize:13,
        color:"gray",
      backgroundColor:"transparent"
      },
      indicatorStyle:{
        top: 5,
        borderRadius: 20,
        left: 0,
        height: 26,
        borderWidth:1,
        borderColor:"red",
        borderStyle:"solid",
        overflow:"hidden",
        backgroundColor:"transparent"
      },
      itemStyle:{
        width:60,
        borderRadius: 20,
        height:34,
      }
    },
    page1_segment4:{
      type:"xz.segment",
      styletype:"2",
      items:["快的","出租车","顺风车","试驾","代驾","顺风车","专车","巴士"],
      style:{
        borderColor:"#ccc"
      },
      selectedTextStyle:{
        color:"#ff7600",
        fontSize:13
      },
      textStyle:{
        fontSize:13,
        color:"gray",
        backgroundColor:"transparent"
      },
      indicatorStyle:{
        top: 5,
        borderRadius: 20,
        left: 0,
        height: 26,
        borderWidth:1,
        borderColor:"#eee",
        borderStyle:"solid",
        overflow:"hidden",
        backgroundColor:"#fff"
      },
      itemStyle:{
        width:60,
        borderRadius: 20,
        height:34,
      }
    },
    listviewtitlewrapper:{
      type:"xz.view",
      root:["listviewtitle"],
      style:{
        borderStyle:"solid",
        borderBottomWidth:0,
        borderRightWidth:0,
        borderTopWidth:0,
        borderLeftWidth:2,
        borderColor:"rgb(255, 102, 51)",
        paddingTop:1,
        paddingBottom:1,
        marginLeft:3,
        marginBottom:2,
        marginTop:3,
      }
    },
    listviewtitle:{
        type:"xz.text",
        text:"商品展示",
        style:{
          fontSize:13,
          marginLeft:4,
          paddingLeft:4,
          color:"gray"
        }
    },

    listview:{
      type:"xz.listview",
      root:["row_innerview"],
      datasource_bind:"GoodsListView.data",
      col:2,
      style:{
      },
      rowStyle:{
        paddingTop:2,
        paddingLeft:2,
        paddingRight:2,
        paddingBottom:2
      }
    },
    row_innerview:{
      type:"xz.view",
      root:["row_image","row_name","row_price"],
      style:{
        backgroundColor:"#fff",
        paddingLeft:4,
        paddingTop:2,
        paddingRight:4,
        flexDirection:"column",
        borderRadius:3
      }
    },
    row_image:{
      type:"xz.image",
      src_bind:"$$rowdata.imageurl",
      style:{
        flex:1,
        height:180
      },
      src:"",
    },
    row_name:{
      type:"xz.text",
      style:{
        fontSize:12,
        color:"#aaa",
        lineHeight:15,
        height:30,
        overflow:"hidden"
      },
      text_bind:"$$rowdata.name",
      text:"未绑定"
    },
    row_price:{
      type:"xz.text",
      style:{},
      text_bind:"$$rowdata.price",
      text:"0.00"
    },
    headerLeftIcon:{
      type:"xz.icon",
      font:"icomoon_e914",
      iconStyle:{color:"#fff",fontSize:20},
      style:{
        common:"righticon"
      },
      onClick:[
        // {"type":"modifyProperty","to":"popover","show":true}
          {"type":"showpage","to":"why"}
      ]
    },
    popover:{
      type:"xz.popover",
      style:{},
      root:[]
    },
    page1_view1:{
      type:"xz.view",
      show:false,
      root:["page1_text1"

    ],
      style:{
        backgroundColor:"rgba(0,0,0,.82)",
        height:100,
        width:"100%",
        flexDirection:"column",
        alignItems:"center",
        justifyContent:"center"
      }
    },
    yunfeiview:{
      type:"xz.view",
      root:["运费区域","实际付款区域"],
      style:{
        backgroundColor:"#fff",
        flexDirection:"column",
        paddingTop:10,
        paddingLeft:10,
        paddingRight:10,
        paddingBottom:10
      }
    },
    运费区域:{
      type:"xz.view",
      root:["运费文本","运费值"],
      style:{
        width:"100%",
        paddingBottom:5,
        flexDirection:"row",
        justifyContent:"space-between"
      }
    },
    运费文本:{
      type:"xz.text",
      text:"运费",
      style:{
        color:"#666666",
        fontSize:13
      }
    },
    运费值:{
      type:"xz.text",
      text:"6.00",
      style:{
        color:"gray",
        fontSize:13
      }
    },
    实际付款区域:{
      type:"xz.view",
      root:["实际付款文本","实际付款值"],
      style:{
        width:"100%",
        flexDirection:"row",
        justifyContent:"space-between"
      }
    },
    实际付款文本:{
      type:"xz.text",
      text:"实付款(含运费)",
      style:{
        color:"#666666",
        fontSize:14
      }
    },
    实际付款值:{
      type:"xz.text",
      text:"6.00",
      style:{
        color:"#FF6633",
        fontSize:14
      }
    },
    page1_view2:{
      type:"xz.view",
      root:["众筹提示文本"],
      style:{
        flexDirection:"column",
        backgroundColor:"#FEF3D9",
        height:40,
        width:"100%",
        justifyContent:"center"
      }
    },
    众筹提示文本:{
      type:"xz.text",
      style:{
        marginLeft:15
      },
      text:"众筹成功!"
    },
    page1_text2:{
      type:"xz.text",
      text:"wolew",
      style:{
        textAlign:"center"
      },
      onClick:[
        {type:"navigate",to:"saoyisao"}
      ]
    },
    page1_text3:{
      type:"xz.text",
      text:"Gotowhy",
      style:{},
      onClick:[
        {type:"navigate",to:"tabbarpage_why"},
      ]
    },
    page1_text1:{
      type:"xz.button",
      text:"ClickMe",
      style:{
        backgroundColor:"rgb(255,42,95)",
        width:200,
        paddingTop:10,
        paddingBottom:10,
        borderRadius:20,
        overflow:"hidden"
      },
      textStyle:{
        textAlign:"center",
        color:"#fff",
        fontSize:14,
      },

      onClick:[
        {type:"modifyStyle",to:"page1_text2",color:"red",fontSize:23},
        {type:"modifyStyle",to:"page1_view1",backgroundColor:"#fff"},
        {type:"modifyProperty",to:"page1_text3",text:"跳转到Page00"}
      ]
    }
  }
};
