module.exports = {
  datasouceconfig:{
    baseurl:"http://imall.yonyou.com"
  },
  datasource:{
    Login:{
      url:"http://imall.yonyou.com/my",
      params:{"userid":"",psw:""},
      data:{},
      lastUpdated:"",
      isFetching:false
    }
  },
  stylepool:{
    stylekeys:["style","iconStyle","textStyle"],
    lefticon:{
      position:"absolute",
      left:3,  width:40,
        height:40,
      top:4
    },
    righticon:{
      position:"absolute",
      right:3,  width:40,
        height:40,
      top:4
    },
    MenuLayoutItem:{
      paddingTop:12,
      paddingBottom:12,
      backgroundColor:"#fff",
      paddingRight:10,
      paddingLeft:10,
      flexDirection:"row",
      justifyContent:"space-between"
    },
    themeColor:{
      color:"red"
    },
    tabtext:{
      fontSize:10,marginTop:2,color:"#929292"
    },
    header:{
      height:48,
      justifyContent:"center",
      alignItems:"center",
      backgroundColor:"rgb(18,181,242)"
    }
  },
  ctlpool:{
    line1:{
      type:"xz.line",
      style:{
        height:1,
        backgroundColor:"#e5e5e5"
      }
    },line2:{
      type:"xz.line",
      style:{
        height:1,
        marginLeft:10,
        backgroundColor:"black"
      }
    },
    righticon:{
      type:"xz.icon",
      font:"icomoon_e92c",
      iconStyle:{color:"#D0CFCF",fontSize:16},
      style:{}
    }
  }
};
